### ISSUE TITLE
Problem when using transfer functions to interpolate between meshes

### ISSUE THREAD

**Issue by lluisjofre** [NaluCFD/Nalu#311]
Turbulent axisymmetric case:

When trying to interpolate the solution from mesh R2 to mesh R3, the input file seems to be missing some part of the transfer functions.

Input file attached:
file:///home/jofre/Downloads/inputJet.i

**Comment by spdomin** [comment]
I will attempt to look at this tomorrow. This is a supported use case and should work. If not, it is a bug in the code.

**Comment by spdomin** [comment]
There are a couple of issues in the input files. Let me start with the first simulation.. I think that there was a copy/paste error:

```
  - name: ioRealm
    mesh: ../Inflows/R3/fuegoPipeInflow.e
    type: external_field_provider
    automatic_decomposition_type: rcb

    field_registration:
      specifications:

        - field_name: velocity_bc
          target_name: [block_7, block_1007]
          field_size: 3
          field_type: node_rank

```

The above ioRealm controls the inflow bc. However, it is missing a interval. The complete block should be:

```
  - name: ioRealm
    mesh: inflow/fuegoPipeInflow.e
    type: external_field_provider
    automatic_decomposition_type: rcb

    field_registration:
      specifications:

        - field_name: velocity_bc
          target_name: [block_7, block_1007]
          field_size: 3
          field_type: node_rank

    solution_options:
      name: myOptions
      input_variables_interpolate_in_time: yes
      input_variables_from_file_restoration_time: 0.0
      input_variables_from_file_periodic_time: 0.50

      options:    
        - input_variables_from_file:
            VELOCITY_BC: velocity_bc
```

Also, in the second simulation, the velocity_bc is providing the data (or attempting it) from the restarted simulation. However, velocity_bc is not a persistent variable. We need to keep ownership of populating velocity_bc by the ioRealm.

Here is an ncdump myRestart.16.0 output:

```
 name_nod_var =
  "density",
  "density.N",
  "density_ra_one",
  "pressure",
  "resolved_turbulent_ke",
  "resolved_turbulent_ke_ra_one",
  "reynolds_stress_1",
  "reynolds_stress_2",
  "reynolds_stress_3",
  "reynolds_stress_4",
  "reynolds_stress_5",
  "reynolds_stress_6",
  "velocity_x",
  "velocity_y",
  "velocity_z",
  "velocity.N_x",
  "velocity.N_y",
  "velocity.N_z",
  "velocity_ra_one_x",
  "velocity_ra_one_y",
  "velocity_ra_one_z" ;
```

I will post the new input files at the next comment.

**Comment by spdomin** [comment]
The second run needs the following:

```
# Interpolation from R2 to R3
  - name: initRealm
    mesh: restart/firstJet.rst
    use_edges: yes
    type: initialization

    field_registration:
      specifications:
        - field_name: velocity
          target_name: block_1
          field_size: 3
          field_type: node_rank

        - field_name: pressure
          target_name: block_1
          field_size: 1
          field_type: node_rank

        - field_name: velocity_ra_one
          target_name: block_1
          field_size: 3
          field_type: node_rank

        - field_name: resolved_turbulent_ke_ra_one
          target_name: block_1
          field_size: 1
          field_type: node_rank

        - field_name: reynolds_stress
          target_name: block_1
          field_size: 6
          field_type: node_rank

    solution_options:
      name: myOptions
      input_variables_from_file_restoration_time: 100.0

      options:
        - input_variables_from_file:
            velocity: velocity
            pressure: pressure
            velocity_ra_one: velocity_ra_one
            resolved_turbulent_ke_ra_one: resolved_turbulent_ke_ra_one
            reynolds_stress: reynolds_stress
```
