### ISSUE TITLE
V27 41b seg-faults in AssembleNodalGradU algorithm when wall functions are active.

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#385]
When activating wall functions,

```
    - wall_boundary_condition: bc_cone
      target_name: surface_10
      wall_user_data:
        user_function_name:
         velocity: wind_energy
        user_function_string_parameters:
         velocity: [mmOne]
        use_wall_function: yes
```

the production V27-41b fails.
