### ISSUE TITLE
ECP 5(c) Generalize mesh motion

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#49]
Relax the requirement to have sliding mesh simulations in the x-direction for 3D.

Also allow for a clean interface between 2D and 3D.

I will handle the code based on the formula provided by @gantech

**Comment by spdomin** [comment]
Just a FYI @NaluCFD/core as my generalized rotation work, which I just pused with support from @gantech, caused minor diffs in a few of the rotating sliding mesh sims.

**Comment by spdomin** [comment]
This looks done. We can re-open when we have more complex use cases. However, now we have an arbitrary flow direction capability via:

```
        - name: mmFront_ss5
          target_name: [block_2]
          omega: 3.14
          unit_vector: [0.0,0.0,1.0]
          centroid_coordinates: [-0.3, 0.0]

```

along with the reference to the wall bc as follows:

```
    - wall_boundary_condition: bc_front_blade
      target_name: surface_5
      wall_user_data:
        user_function_name:
         velocity: wind_energy
        user_function_string_parameters:
         velocity: [mmFront_ss5]
        mixture_fraction: 1.0

```
